# Generated by Django 4.1.13 on 2025-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionJugos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
